### ISSUE TITLE
Spamming Bank during Combat

### ISSUE THREAD

**Issue by Magnificoman** [PBLord/Parabot-Script-errors#12] opened 2018-02-03 23:00 UTC
The script will spam ::bank when it runs out of restore potions. If you're in combat with a quick hitting monster, it'll just keep spamming bank. 

Eventually the monster will die and you should be able to bank, but sometimes it cancels the bank again with the new monster, and continues to spam ::bank.

I feel this could alert the staff about people botting.

The solution would be to not attack another creature until the banking command is finished. So I guess you could just make it so when there's no restores left in the inventory, do not initiate combat.

_Cheers_

**Comment by George-Farrell** [comment] 2018-02-04 14:18
The issue is that if it is hitting you and you have nothing in inv it will try to get them as its higher on the priority list, so it will spam till it has them and the script will not attack unless it has the potions. I have added a fail-safe that it will clear the message box to make sure it is empty before typing again.

**Comment by Magnificoman** [comment] 2018-02-04 16:27
The script keeps typing it out and spamming it. It's not just spamming enter irrationally, it'll just try to bank 20 times in a single fight sometimes, which is suspicious.

**Comment by George-Farrell** [comment] 2018-02-17 09:59
Fixed in the latest Build

**Closed as completed by George-Farrell** 2018-02-17 09:59 UTC
